server:
  port: 7002
spring:
  datasource:
    url: jdbc:mysql://localhost:12345/flyway
    username: root
    password: 123...
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    # 是否开启 flyway
    enabled: true
    # 连接的数据库为空库时, 是否初始化
    baseline-on-migrate: true
    # 默认加载 SQL 文件路径
#    locations=classpath:db/migration
